spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liner
    username: liner-feed-api
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true